############################
## Author
############################

author:
  name: "George Kousis"
  image: author4.jpeg
  greeting: "The coding chef"
  # icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/kusius
  - linkedin: https://www.linkedin.com/in/george-kousis/
  - email: mailto:gmkousis@gmail.com
 

###############################
## OpenGraph & Twitter Cards
###############################

title: "George Kousis"
description: "Demo site build with Qubt & Hugo"
images:
  - thumbnail.jpeg