baseURL = 'https://kusius.github.io/'
languageCode = 'en-us'
title = 'The coding chef'
theme = 'qubt'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = "G-WLSN57SKFS"
enableRobotsTXT = true

[params]
show_reading_time = true

[[params.ananke_socials]]
name = "X"
url = "https://x.com/gmkroute"

[[params.ananke_socials]]
name = "GitHub"
url = "https://github.com/kusius"

[[params.ananke_socials]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/george-kousis/"